travis:
  secure:
    BINSTAR_TOKEN: Af8eA1i2L5X5/FZq7s62Lt6jkCoVsI+0719DUh9M0TsUFaVRiiiwIvsgJzlRQKaGWIIhthfChrtANgx61Tr1sVizD0DzKut9+fl6y2c26n+Mzbe17jeOlJDevE/mIX9er4A6/Ew5NF3LZZIEzZczHnZQSPAhwLvdAW8YbKxaVB8ZGJ6MtgM1dCgxAjHhpriuF8PspRIYdnvMsBGcNwENzSRpdeOBXHOuXYJKmP8jrNRnC8W7ejPEgJbU/43kzL9VRBC7Awib4xN5e3F35ZKTHdJGBonaUp53nxmXdJM7v42gd+nitIGx7AXBqCxTVy2kmqBmpoGbLyuzGjitUGqT1yUBAZZJxBcK0w6DxtEDeyS53E3Dt2365Hd4kp4jr1wujK6jd6tVTWT0aouGhPR+vhEPrySKJ3MjyJ1XzU30Z0qtR+jY6vWceA4FvzriCCSLlXM96CEknBDAyV1LOG2HgEOOFMCzzUeLFS4sR6+NRKyrZrLgvPYY3cc8Xs3lng1RST9Pt6sQ3Lb5887uTLX8XYKiwRsojuYW6oneXY6Ynmx1S+FrjpeIpRnVJA1sdgX2hWB0P/9vLLJ93MezotYaNHRq5YJyZi8cZDj8Pv0aSf59rxpWlTWmAPFkVi/B0jn544N98LPJMMULTpBQIVomqdN70ufvdYpAsqxcXxwUoo0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
